version: 2
jobs:
  build-examples:
    docker:
      - image: stellargroup/hpx:dev
    working_directory: /tutorials
    steps:
      - checkout:
          path: /tutorials
      - run:
          name: Configuring
          command: |
            mkdir -p build
            cd build
            cmake -G"Ninja" -DCMAKE_BUILD_TYPE=Debug /tutorials/examples
      - run:
          name: Building examples
          command: |
            cd build
            ninja -j2 tutorial

workflows:
  version: 2
  build-examples-nightly:
    triggers:
      - schedule:
          cron: "0 0 * * * "
          filters:
            branches:
              only:
                - master
    jobs:
      - build-examples
  build-examples-push:
    jobs:
      - build-examples

